# Generated by Django 4.2.11 on 2024-04-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintonbooking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.RemoveField(
            model_name='bookingform',
            name='email',
        ),
        migrations.AddField(
            model_name='bookingform',
            name='student_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
